spring:
  datasource:
    url: jdbc:mysql://spring-boot-capstone.cr2cex6a6lgf.ap-northeast-2.rds.amazonaws.com:3306/noone?useUnicode=true&characterEncoding=utf8
    username: admin
    password: 34693469
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: no-one
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

  output:
    ansi:
      enabled: always #콘솔 색상
  config:
    import:
      - classpath:appConfig.yml
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  jpa.hibernate:
    naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # ???? ???? ?? ??
    naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
  security:
    user:
      name: user
      password: 1234
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB

server:
  port: 8080
  servlet:
    session:
      timeout: 60m
  tomcat:
    remoteip:
      remote-ip-header: "x-real-ip"
      protocol-header: "x-forwarded-proto"

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: likelion-noone
    credentials:
      access-key: AKIAWXUB7VDDVGIOQF3L
      secret-key: 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
      stack:
        auto: false

jwt:
  secret:
    key: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M